# This file configures the static analysis as well as the linter
# for the package.

include: package:flutter_lints/rules.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - use_key_in_widget_constructors
    - always_declare_return_types
    - camel_case_types
    - library_names
    - avoid_print
    - annotate_overrides
